default_star_ccm_plus = r"E:\Siemens\STARCCM\18.04.008-R8\STAR-CCM+18.04.008-R8\star\bin"
default_star_ccm_version = "18.04.008-R8"
star_ccm_plus_install_dir = r"E:\Siemens\STARCCM"
star_ccm_plus_bkup_install_dir = r"C:\Siemens"
zip_exe = r"C:\Program Files\7-Zip\7z.exe"
ffmpeg_exe = r"E:\Program Files\ffmpeg\bin\ffmpeg.exe"
